### ISSUE TITLE
Inline styles need to be put into a stylessheet

### ISSUE THREAD

**Issue by robertDurst** [BlockAndJerrys/block-and-jerrys#116]

**Comment by tangsauce** [comment]
Are styles in a `.css` better than inline?

**Comment by robertDurst** [comment]
I believe so. Much cleaner

**Comment by tangsauce** [comment]
What are your thoughts on `styles` object at the top of component files such as in https://github.com/robertDurst/blockandjerrys/blob/master/src/components/infoCart.jsx
