### ISSUE TITLE
Configure a Bitcoin Core --> BTCD --> LND as recommended by a Bitcoin Core guy

### ISSUE THREAD

**Issue by robertDurst** [BlockAndJerrys/block-and-jerrys#118]

**Comment by tangsauce** [comment]
Tutorials were mentioned in the original CoinDesk article about blockandjerrys:

- https://www.coindesk.com/how-to-send-a-lightning-transaction-even-if-you-may-not-want-to/
- https://blockstream.com/2018/02/02/lightning-instant-bitcoin-transacting-tutorial.html

**Comment by robertDurst** [comment]
Here is what I used to connect to the mainnet with LND: https://medium.com/@zaptrem/mainnet-lightning-run-lnd-zap-desktop-on-windows-f73cf78dd633

**Comment by robertDurst** [comment]
In progress.. dont actually need an issue for this
