### ISSUE TITLE
Connect the Lightning Network Mainnet ⚡

### ISSUE THREAD

**Issue by robertDurst** [BlockAndJerrys/block-and-jerrys#122]

**Comment by robertDurst** [comment]
Conducted first successful mainnet ice cream purchase this morning. Need to connect things more smoothly, but I know it works.

**Comment by taariq** [comment]
Nice!!!!!

**Comment by taariq** [comment]
We need to embed this date into the blockchain!

**Comment by robertDurst** [comment]
Lighting-app neutrino wallet to Block and Jerrys ✔️
